# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answers_questionquiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='correct_number',
        ),
        migrations.AddField(
            model_name='answers',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionQuiz'),
        ),
    ]
