# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180513_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionquiz',
            name='question_theme',
            field=models.CharField(default='', max_length=200),
        ),
    ]
